name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.0
  keyboard_invoker: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  protobuf: ^3.1.0
  provider: ^6.1.2
  syncfusion_flutter_charts: ^26.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
